apiVersion: apps/v1 # version of the manifest
kind: Deployment
metadata:
    name: secret-notepad
spec:
    selector:
        matchLabels:
            app: secret-notepad
    replicas: 1 # Number of replicas (pods) that will be created for this deployment
    template:
        metadata:
            labels:
                app: secret-notepad
        spec:
            containers:
                - name: secret-notepad
                  image: secret-notepad:1.0
                    # Image that will be used to containers in the cluster, local image, nothing to pull
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 1234